### ISSUE TITLE
Is possible to obtain a non-absolute values gravity changes time-series?

### ISSUE THREAD

**Issue by MiguelonGonzalez** [jkennedy-usgs/heavy-mirror#2]
Hello again,

I am using Heavy to estimate the gravimetry time-series generated by changes in aquifer storage. In the hydrogeological model I am working on ([ExampleData.zip](https://github.com/jkennedy-usgs/heavy-mirror/files/12122806/HeavyExample.zip)), the piezometric time series of the observation point **fluctuates** generating a concave curve upwards: it decreases and then increases exceeding the initial piezometric value.

I have realized that the gravity time-series that Heavy calculates for me is made up of **absolute values**, not including sign (negative or positive) of the gravity change. Since Heavy calculates gravity changes with respect to the value of the first time-step, this generates in the gravimetric time series a fictitious fluctuation when (during water table recovery) the piezometric value exceeds the initial value (reference point, ie. zero gravimetric difference).

I open the issue then to confirm that the output is intended (not a execution problem of mine) and to know if there is the **option of obtaining a non-absolute gravimetric time-series**, in which the changes include the direction of the difference (positive or negative sign). I think this could be very useful when comparing the estimated gravimetric signal with any other variable.

You can find attached the data I am using.

Thank you very much!

![image](https://github.com/jkennedy-usgs/heavy-mirror/assets/75794654/30b74b75-72cb-4015-b9c3-59c4df4862c7)

**Comment by jkennedy-usgs** [comment]
I'm not sure I understand the question, Heavy should definitely include the sign of the gravity change - if total storage goes up, gravity increases; if it goes down, gravity decreases. Change in storage (mass) is calculated relative to the model's first time step. 

What you are seeing could happen if the elevation of the gravity stations is wrong - if the piezometric head rises above the elevation of a gravity station, the additional mass will "pull up" on the station, thus decreasing gravity. You could try adding several meters to your station elevation (so they are definitely above the water table) to see if the results are more reasonable. For some reason your plot is backwards for time steps 0-125 - gravity should definitely decrease if storage (e.g., pz level) is decreasing. 

In any case I am away next week and will have to get back to this. Thanks for pointing it out.

**Comment by MiguelonGonzalez** [comment]
The piezometric level on the example given is **334 metres under the topogrphic surface** where the gravimeter relies upon -the surface is at 2148 mabsl and the water table at about 1814. So the reason you're pointing out could not be ocurring in this case. Nevertheless, I have run it again with several hundred of meteres added to the surface topography and the graphic results are the same.

Don't know why, but in my case Heavy is not indicatin the sign of the gravimetric change, it just simply output the absolute value of the change, as evidenced by the data attached to the current issue and [this one](https://github.com/jkennedy-usgs/heavy-mirror/issues/1). In the latter one, a decreasing piezometric level is output from Heavy as a gravimetric increasing time-series, when it should output the contrary (a decreasing).

Please let me know if you found out why when you come back. Thank you!

**Comment by jkennedy-usgs** [comment]
Hi @MiguelonGonzalez , I'm very glad you brought this up, there were a couple of bugs. One had to do with reading CONSTANT values from the .lpf file, and the other with the sign of the density change when head was above the starting head. Turns out that all of the models I was using for test cases used arrays of parameters for defining SY, and mainly had declining storage.

I think both issues are fixed, could you give it another try? Both the code.usgs.gov and github sites should be up to date. Here is some output using your test location: 
![image](https://github.com/jkennedy-usgs/heavy-mirror/assets/9754449/454791a5-a0c6-4117-8b27-facb13bbc416)

**Comment by MiguelonGonzalez** [comment]
Hi @jkennedy-usgs, thank you very much for debugging and upgrading the code.

I have just executed the code with the data of both issues (#1 and #2) and now the output is correct: storage decrease means gravity decreases.

Cheers!
